### ISSUE TITLE
a bug ——RuntimeError: DataLoader worker (pid 2104) is killed by signal: Bus error.

### ISSUE THREAD

**Issue by Ai-is-light** [TwentyBN/something-something-v2-baseline#6]
Thanks for your good paper and this repo. I run these codes under the docker environment. I'm confused with some bugs. When I set the num_works = 1 and the batch_size=4, and use, CUDA_VISIBLE_DEVICES=0,1 python train.py -c configs/config_model1.json -g 0,1 --use_cuda, it will work. In fact I have 8*1080Ti, When I set the num_works>1(like 4), or the batch_size >4(like 8), it will get the error like 
> Output folder for this run -- trained_models/model3D_1
 > Creating model ... !
 !#! No checkpoint found at 'trained_models/model3D_1/model_best.pth.tar'
 > Using 1 processes for data loader.
 > Number of dataset classes : 174
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "train.py", line 376, in <module>
    main()
  File "train.py", line 186, in main
    validate(val_loader, model, criterion, train_data.classes_dict)
  File "train.py", line 332, in validate
    output, features = model(input_var, config['save_features'])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 110, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 36, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 29, in scatter
    return scatter_map(inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 16, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 18, in scatter_map
    return list(map(list, zip(*map(scatter_map, obj))))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 14, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 74, in forward
    outputs = comm.scatter(input, ctx.target_gpus, ctx.chunk_sizes, ctx.dim, streams)
  File "/opt/conda/lib/python3.6/site-packages/torch/cuda/comm.py", line 158, in scatter
    outputs.append(chunk.cuda(device, non_blocking=True))
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 178, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 2351) is killed by signal: Bus error.

**Comment by Ai-is-light** [comment]
and, would mind sharing your environment requirement.txt?? thanks

**Comment by raghavgoyal14** [comment]
Prematurely referring to some posts that might be relevant to your situation (since you are using a docker container):

- https://github.com/pytorch/pytorch/issues/5040
- https://github.com/pytorch/pytorch/issues/2244

Let me know if it helps.
Thanks for trying out the repo.

P.S. a `requirement.txt` or a conda equivalent is next on my list

**Comment by Ai-is-light** [comment]
Thx
